### ISSUE TITLE
Adding feature

### ISSUE THREAD

**Issue by dimakiss** [dimakiss/Udemy_bot#7]
Adding the option of reading from a previous urls text file and make sure that urls are not repeating.

**Comment by SmokE-PGF** [comment]
This was already done on #5 :)

**Comment by dimakiss** [comment]
Yes, I see :)
But I meant skipping the already enrolled courses.
Fixing now the `add_links` method :)

**Comment by SmokE-PGF** [comment]
Yes it already skips any courses that area already enrolled:
line 210 using the url_is_new function and only tries to enrol in new courses in line 232 :)

**Comment by dimakiss** [comment]
Yes, you are totally right, I missed that :)
