### ISSUE TITLE
Selenium package gives error installing with pip3

### ISSUE THREAD

**Issue by Porkechebure** [dimakiss/Udemy_bot#9]
RUN pip3 install -r requirements.txt
 ---> Running in 88829269d1f6
Collecting bs4==0.0.1
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Collecting requests==2.23.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting lxml>=4.6.2
  Downloading lxml-4.6.2-cp39-cp39-manylinux1_x86_64.whl (5.4 MB)
ERROR: Could not find a version that satisfies the requirement selenium==1.25.9
ERROR: No matching distribution found for selenium==1.25.9

**Comment by dimakiss** [comment]
I added ">" to "selenium>=1.25.9".
I think this will fix the issue.
Thanks for your note :)

**Comment by Porkechebure** [comment]
> I added ">" to "selenium>=1.25.9".
> I think this will fix the issue.
> Thanks for your note :)

Yeah that's what I did too.
Thanks
